### ISSUE TITLE
Submit to packagist.org

### ISSUE THREAD

**Issue by jongotlin** [getanewsletter/api-php#1]
Please submit to packagist.org and remove repositories part in composer.json.

Please also submit a stable version.

**Comment by IlianIliev** [comment]
Thanks for the input. We are not PHP developers so the package does not implement the full API functionality at the moment but we will do our best to improve it.

**Comment by jongotlin** [comment]
I mean stable in sense that I don't need `"minimum-stability": "dev"`. You just have to create and push a git tag.

To submit to packagist just create an account and follow the instructions.

**Comment by jonlil** [comment]
I'm really sad for quite late response but now its published on packagist.

https://packagist.org/packages/getanewsletter/api-php

**Comment by jongotlin** [comment]
:+1: Thanks
